[package]
name = "s07-taskbar"
version = "0.0.0"
edition = "2021"

[workspace]

[dependencies]
windows = { version = "0.61", features = [
  "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi",
  "Win32_UI_Accessibility", "Win32_System_Com", "Win32_System_Ole", "Win32_System_Variant",
] }
