import { PI, TAU, cl, hr } from "../math";
import { OL, PAPER, STEEL, DARK } from "../palette";
import { rrP, elP, shp, seg, lines } from "../pen";
import { foldHW, morph } from "../fold";
import { BOARD } from "./props";
import { BOLT } from "../scenes";
export function drawItems(x: any,c: any,arms: any,u: any,_t: any,lw: any){const k=c.hold,a=cl(c.p.holdA.x);if(!k||a<.02)return;const L=arms[0],R=arms[1],tg=c.tg||{};x.save();x.globalAlpha*=a;x.lineWidth=lw;x.strokeStyle=OL;x.lineJoin='round';
if(k==='sheet'){const lx=L.hx+1*u,ty=L.hy-17*u,w=43*u,h=34*u;shp(x,rrP(lx,ty,w,h,1.5*u),PAPER,u);x.beginPath();x.moveTo(lx+w-6*u,ty);x.lineTo(lx+w-6*u,ty+6*u);x.lineTo(lx+w,ty+6*u);x.stroke();
for(let i=0;i<4;i++){const y=ty+9*u+i*6*u,ww=(24+10*hr(i*3.3+c.pageSeed*7.1))*u;if(tg._line===i&&tg._prog!=null){x.fillStyle='rgba(217,119,87,0.35)';x.fillRect(lx+4*u,y-2*u,ww*tg._prog,4*u);}x.strokeStyle='#B4B2A9';x.lineWidth=Math.max(.8,1.4*u);x.beginPath();x.moveTo(lx+4*u,y);x.lineTo(lx+4*u+ww,y);x.stroke();}x.strokeStyle=OL;x.lineWidth=lw;
if(tg._carry){x.save();x.translate(R.hx,R.hy);x.rotate(-.5);shp(x,rrP(-4*u,-2*u,30*u,24*u,1.5*u),PAPER,u);lines(x,0,5*u,20*u,3,5*u,'#B4B2A9',u,c.pageSeed+1);x.restore();}}
if(k==='paper'){const m=tg._fold||0,fr=cl((m-.6)/.3),cxp=(1-fr)*(R.hx-foldHW(m)*u-3*u)+fr*(R.hx+2*u),cyp=R.hy+(1-fr)*1*u-fr*2*u;x.translate(cxp,cyp);if(m>=1)x.rotate(-.15);shp(x,morph(m,u),PAPER,u);if(m>.33&&m<.9){x.strokeStyle='#B4B2A9';x.lineWidth=Math.max(.6,1.2*u);x.beginPath();x.moveTo(0,-15*u);x.lineTo(0,15*u);x.stroke();x.strokeStyle=OL;}}
if(k==='lens'){const lx=R.hx+11*u,ly=R.hy-11*u;seg(x,R.hx,R.hy,lx-3*u,ly+7*u,3.6*u,DARK,lw);x.save();x.beginPath();x.arc(lx,ly,10*u,0,TAU);x.clip();x.fillStyle='rgba(214,230,246,0.9)';x.fill();if(c.prop==='board'){x.translate(lx,ly);x.scale(1.8,1.8);x.translate(-lx,-ly);x.fillStyle=PAPER;x.fillRect(64*u,-71*u,40*u,49*u);BOARD(x,u,1,tg._hit);}x.restore();shp(x,elP(lx,ly,10*u,10*u),null,u);x.lineWidth=Math.max(1,3*u);x.strokeStyle=DARK;x.beginPath();x.arc(lx,ly,10*u,0,TAU);x.stroke();x.strokeStyle='#FFFFFF';x.lineWidth=Math.max(.8,1.6*u);x.beginPath();x.arc(lx-1*u,ly-1*u,6*u,PI*1.1,PI*1.45);x.stroke();}
if(k==='net'){const ph=c.p.pole.x,d=[Math.sin(ph),-Math.cos(ph)],b0=[R.hx-d[0]*9*u,R.hy-d[1]*9*u],b1=[R.hx+d[0]*58*u,R.hy+d[1]*58*u],hc=[R.hx+d[0]*73*u,R.hy+d[1]*73*u];c.hoop=[hc[0]/u,hc[1]/u];
const pn=[Math.cos(ph),Math.sin(ph)],RA=15*u,RB=8*u,rim=(th_: any)=>[hc[0]+d[0]*RA*Math.cos(th_)+pn[0]*RB*Math.sin(th_),hc[1]+d[1]*RA*Math.cos(th_)+pn[1]*RB*Math.sin(th_)],A_=rim(PI),B_=rim(0),tip=[hc[0]+pn[0]*30*u-d[0]*3*u,hc[1]+pn[1]*30*u-d[1]*3*u];const bag=()=>{x.beginPath();x.moveTo(A_[0],A_[1]);for(let i=1;i<=12;i++){const q=rim(PI+PI*i/12);x.lineTo(q[0],q[1]);}x.quadraticCurveTo(B_[0]+pn[0]*22*u,B_[1]+pn[1]*22*u,tip[0],tip[1]);x.quadraticCurveTo(A_[0]+pn[0]*24*u,A_[1]+pn[1]*24*u,A_[0],A_[1]);x.closePath();};bag();x.fillStyle='rgba(250,249,245,0.62)';x.fill();x.save();bag();x.clip();x.strokeStyle='rgba(95,94,90,0.45)';x.lineWidth=Math.max(.5,.9*u);x.beginPath();for(let i=-8;i<=8;i++){const o=i*4.5*u;x.moveTo(hc[0]+pn[0]*o-d[0]*40*u,hc[1]+pn[1]*o-d[1]*40*u);x.lineTo(hc[0]+pn[0]*(o+50*u)+d[0]*40*u,hc[1]+pn[1]*(o+50*u)+d[1]*40*u);x.moveTo(hc[0]+pn[0]*o+d[0]*40*u,hc[1]+pn[1]*o+d[1]*40*u);x.lineTo(hc[0]+pn[0]*(o+50*u)-d[0]*40*u,hc[1]+pn[1]*(o+50*u)-d[1]*40*u);}x.stroke();x.restore();x.lineWidth=Math.max(.6,1.2*u);bag();x.stroke();x.lineWidth=lw;if(tg._page!=null&&tg._page>=1.33&&tg._page<2.45){const s=1-.45*cl((tg._page-1.33)/.4);drawWebPage(x,hc[0]+pn[0]*15*u,hc[1]+pn[1]*15*u,s,u,lw,ph);}
seg(x,b0[0],b0[1],b1[0],b1[1],3.2*u,'#C9A27A',lw);x.lineWidth=Math.max(1,2.6*u);x.strokeStyle=DARK;x.beginPath();x.ellipse(hc[0],hc[1],15*u,8*u,ph-PI/2,0,TAU);x.stroke();}
if(k==='wrench'){const bx=BOLT[0]*u,by=BOLT[1]*u,ang=Math.atan2(R.hy-by,R.hx-bx),len=Math.hypot(R.hx-bx,R.hy-by);if(c.pAng!=null){let dA=ang-c.pAng;dA=Math.atan2(Math.sin(dA),Math.cos(dA));if(dA<0)c.boltAng+=dA;}c.pAng=ang;x.translate(bx,by);x.rotate(ang);shp(x,rrP(9*u,-3.6*u,len-6*u,7.2*u,3.4*u),STEEL,u);shp(x,[[-12*u,-10*u],[12*u,-10*u],[12*u,10*u],[-12*u,10*u],[-12*u,4.5*u],[-4*u,4.5*u],[-4*u,-4.5*u],[-12*u,-4.5*u]].map((p: any)=>[p[0]+3*u,p[1]]),STEEL,u);}
x.restore();}
export function drawWebPage(x: any,px: any,py: any,s: any,u: any,lw: any,rot: any){x.save();x.translate(px,py);x.rotate(rot||0);x.scale(s,s);x.lineWidth=lw;x.strokeStyle=OL;shp(x,rrP(-10*u,-8*u,20*u,16*u,2*u),PAPER,u);x.fillStyle='#E3E0D5';x.fillRect(-9*u,-7*u,18*u,3.5*u);x.fillStyle='#D97757';x.beginPath();x.arc(-6.5*u,-5.2*u,1*u,0,TAU);x.fill();x.strokeStyle='#378ADD';x.lineWidth=Math.max(.8,1.4*u);x.beginPath();x.moveTo(-7*u,0);x.lineTo(3*u,0);x.stroke();lines(x,-7*u,3.5*u,12*u,2,3*u,'#B4B2A9',u,2);x.restore();}
