// Pikselowe rekwizyty i znaczki dla modelu Pixel-art. Znak = kolor z PROP_PAL, '.' = przezroczyste.
export const PROP_PAL: Record<string, string> = {
  k: '#2B1D16', l: '#D3D1C7', m: '#B4B2A9', s: '#888780', d: '#2C2C2A', t: '#5DCAA5',
  c: '#D97757', p: '#FAF9F5', b: '#85B7EB', y: '#EF9F27', w: '#FFFFFF', h: '#F2AE92', g: '#8C887E',
};

export const SPRITES: Record<string, string[]> = {
  desk: [
    '...........kkkkkkk',
    '...........kdddddk',
    '...........kdtcddk',
    '...........kddttdk',
    '...........kdcdddk',
    '...........kkkkkkk',
    '..............kk..',
    'kkkkkkkkkkkkkkkkkk',
    'kssssssssssssssssk',
    '.k..............k.',
    '.k..............k.',
    '.k..............k.',
  ],
  crt: [
    'kkkkkkkkkk',
    'kllllllllk',
    'klddddddlk',
    'kldtttddlk',
    'klddddddlk',
    'kldttdddlk',
    'klddddddlk',
    'kldtttddlk',
    'klddddddlk',
    'kllllllllk',
    'kllllllllk',
    'klsslllllk',
    'kllllllllk',
    'kkkkkkkkkk',
    '...kkkk...',
    '.kkkkkkkk.',
  ],
  board: [
    'kkkkkkkk',
    'kppppppk',
    'kpccpppk',
    'kppttppk',
    'kpppccpk',
    'kptttppk',
    'kppppppk',
    'kkkkkkkk',
    '..k..k..',
    '.k....k.',
    'k......k',
  ],
  machine: [
    '.kkkkkkkk.',
    'kmmmmmmmmk',
    'kmmmmddmmk',
    'kmmmmttmmk',
    'kmmmmmmmmk',
    'kmmssssmmk',
    'kmmsyysmmk',
    'kmmssssmmk',
    'kmmmmmmmmk',
    'kkkkkkkkkk',
  ],
  pillow: [
    '.kkkkkkkkkkkk.',
    'kppppppppppppk',
    'kppppppppppppk',
    '.kkkkkkkkkkkk.',
  ],
  lens: [
    '.kkk.',
    'kbbbk',
    'kbwbk',
    '.kkkk',
    '....k',
  ],
  net: [
    '.kkkkk.',
    'k.k.k.k',
    'kk.k.kk',
    'k.k.k.k',
    '.kkkkk.',
    '...k...',
    '...k...',
  ],
  paper: [
    'kkkk',
    'kppk',
    'kkpk',
    'kppk',
    'kkkk',
  ],
  wrench: [
    'k...ss',
    'ssssss',
    'k...ss',
  ],
  mug: [
    'kkk.',
    'kyyk',
    'kyyk',
    'kkk.',
  ],
  z: [
    'kkk',
    '..k',
    '.k.',
    'k..',
    'kkk',
  ],
  spark: [
    '.y.',
    'yyy',
    '.y.',
  ],
  bang: [
    'ccccc',
    'ccwcc',
    'ccwcc',
    'ccwcc',
    'ccccc',
    'ccwcc',
    'ccccc',
    '.c...',
  ],
};
SPRITES.sheet = SPRITES.paper;

/** Kotwica rekwizytu: lewy dolny róg w jednostkach u względem podstawy zwierzaka (jak w props.ts). */
export const PROP_ANCHOR: Record<string, [number, number]> = {
  desk: [28, 0], crt: [80, 0], board: [64, 0], machine: [64, 0], pillow: [-72, 0],
};
