LangString addOrReinstall ${LANG_POLISH} "Dodaj lub zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Już zainstalowano"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz, co chcesz zrobić, i kliknij Dalej."
LangString appRunning ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiony. Zamknij go i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiony.$\nKliknij OK, aby go zamknąć."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz operację do wykonania."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz, jak zainstalować ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (instalacja starszej wersji bez odinstalowania jest wyłączona w tym instalatorze)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć ${PRODUCTNAME}. Zamknij go i spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Nowsza wersja ${PRODUCTNAME} jest już zainstalowana. Instalowanie starszej wersji nie jest zalecane; jeśli naprawdę jej potrzebujesz, najpierw odinstaluj bieżącą. Wybierz, co chcesz zrobić, i kliknij Dalej."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "W systemie jest zainstalowana $R4 wersja ${PRODUCTNAME}. Zalecamy odinstalowanie jej przed instalacją. Wybierz, co chcesz zrobić, i kliknij Dalej."
LangString silentDowngrades ${LANG_POLISH} "Instalacja starszej wersji jest wyłączona w tym instalatorze, więc instalacja cicha nie może kontynuować. Użyj instalatora graficznego.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie można odinstalować."
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2. Aplikacja bez niego nie działa. Uruchom instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Błąd: nie udało się pobrać WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pobrano instalator WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie instalatora WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Błąd: instalacja WebView2 zakończyła się kodem $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Zainstalowano WebView2"
LangString deleteAppData ${LANG_POLISH} "Usuń dane aplikacji (ustawienia)"
